version: "3.9"
services:
  api_container:
    build:
      context: .
      dockerfile: API.Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - neo4j_container
      - postgresql_container
    networks:
      - social_app_network

  neo4j_container:
    image: "neo4j"
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: neo4j/hicaropassword
    volumes:
      - neo4j-data:/data
    networks:
      - social_app_network

  postgresql_container:
    build:
      context: .
      dockerfile: DB.Dockerfile
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgresql-data:/var/lib/postgresql
    networks:
      - social_app_network

volumes:
  neo4j-data:
  postgresql-data:


networks:
  social_app_network:
