version: "3.9"
services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - NEO4J_BOLT_URL="bolt://neo4j:password@localhost:7687"
    depends_on:
      - neo4j
      - mysql
  neo4j:
    image: "neo4j"
    ports:
      - "7474:7474"
      - "7687:7687"
  mysql:
    image: "mysql"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
